version: '3.8'

services:
  mydb:
    image: mysql
    container_name: streaming-ac-container
    environment:
      MYSQL_ROOT_PASSWORD: doc1602ker
      MYSQL_DATABASE: streaming_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: upswedr
    ports:
      - "6033:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data: